"use client";

import React from "react";
import Link from "next/link";
import { HomeOutlined } from "@ant-design/icons";
import { ChevronLeft } from "lucide-react";

export default function TrademarkPolicy() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header Section */}
      <div className="bg-gradient-to-r from-[#AF2322] to-[#8B1B1B]">
        <div className="app-container py-12">
          <div className="flex items-center justify-between mb-4">
            <nav className="flex items-center space-x-2 text-white/80 text-xs">
              <Link
                href="/"
                className="text-white hover:text-white transition-colors"
              >
                <HomeOutlined className="text-lg" />
              </Link>
              <span>/</span>
              <Link
                href="/public/terms-of-service"
                className="text-white hover:text-white transition-colors"
              >
                Terms of Service
              </Link>
              <span>/</span>
              <span className="text-white">Trademark Policy</span>
            </nav>
          </div>
          <h1 className="text-4xl font-bold text-white mb-4">
            Trademark Policy
          </h1>
          <p className="text-white/90 text-lg">
            Protecting our brand and community identity
          </p>
        </div>
      </div>

      {/* Main Content */}
      <div className="app-container">
        <div className="bg-white rounded-lg shadow-sm p-8 lg:p-12">
          {/* Back Link */}
          <Link
            href="/public/terms-of-service"
            className="inline-flex items-center text-[#AF2322] hover:text-[#8B1B1B] mb-8 transition-colors"
          >
            <ChevronLeft className="mr-2" />
            Back to Terms of Service
          </Link>

          <div className="prose prose-lg max-w-none">
            {/* Introduction */}
            <div className="mb-10">
              <p className="text-gray-700 leading-relaxed text-base">
                This policy is part of our Terms of Service. By using or
                accessing the Platform, you agree to our Terms of Service as
                well as the rest of our Policies. We reserve the right to amend
                this Trademark Policy at any time including any permissions
                contained herein.
              </p>
            </div>

            {/* Purpose Section */}
            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
                PURPOSE
              </h2>
              <p className="text-gray-700 leading-relaxed text-base">
                We support our tight-knit Community of aviation enthusiasts. To
                keep our Community thriving, we need to safeguard the proper use
                of our Trademarks. Our Trademarks represent us and help maintain
                Fly-Inn's strong association with quality and dependability. Our
                Trademarks symbolize our identity and our reputation for quality
                and dependability and carry with them the substantial goodwill
                generated by our Community. Therefore, this policy sets out
                general guidelines for using our trademarks to facilitate and
                guarantee their correct use by others to prevent confusion in
                the public.
              </p>
            </section>

            {/* Definitions Section */}
            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
                DEFINITIONS
              </h2>
              <p className="text-gray-700 leading-relaxed text-base">
                According to US Patent and Trademark law, a trademark is "any
                word, phrase, symbol, design, or a combination of these things
                that identifies your goods or services. It is how customers
                recognize you in the marketplace and distinguish you from your
                competitors."
              </p>
              <p className="text-gray-700 leading-relaxed text-base mt-4">
                Accordingly, and for the purpose of simplicity, FlyInn, LLC
                defines our Trademarks as:
              </p>
              <ul className="list-disc ml-8 mt-4 space-y-2 text-gray-700 text-base">
                <li>Our names (FlyInn, LLC; FlyInn, Fly-Inn)</li>
                <li>
                  Our logos (the red biplane with FLY-INN on the attitude
                  indicator and any part thereof)
                </li>
                <li>Squawks (blog)</li>
                <li>AlphaHost and the AlphaHost Ribbon</li>
                <li>
                  Any other identifiers and branding including, but not limited
                  to, our slogans, taglines, songs, sounds, icons, packaging,
                  color palette, mascots, typography, design elements, voice,
                  tone, designs, graphics, videos, and specially designed
                  photography and presets
                </li>
              </ul>
              <p className="text-gray-700 mt-4 text-base">
                Collectively referred to as "Trademarks."
              </p>
            </section>

            {/* What is not allowed Section */}
            <section className="mb-10">
              <div className="bg-red-50 border border-red-200 rounded-lg p-6">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  What is NOT Allowed:
                </h2>
                <ol className="list-decimal ml-6 space-y-3 text-gray-700 text-base">
                  <li>
                    Using any identifiers that are confusingly similar to
                    Fly-Inn's Trademarks
                  </li>
                  <li>
                    Using any of our Trademarks or any part of our Trademarks
                    (including style and design elements) in combination with:
                    <ul className="list-disc ml-6 mt-2 space-y-1 text-gray-600 text-sm">
                      <li>
                        Any of your trademarks, service marks or logos, or any
                        part thereof
                      </li>
                      <li>The name of your business</li>
                      <li>
                        The name of your website or domain registration (e.g.,
                        "flyinnrentals.com")
                      </li>
                      <li>
                        The names or handles of any of your social media
                        accounts (e.g., "FlyInn Bob")
                      </li>
                      <li>
                        Your business purpose (e.g., "Fly-Inn Cleaning Service")
                      </li>
                      <li>Any other generic, common or descriptive term</li>
                    </ul>
                  </li>
                  <li>
                    Using our Trademarks as keywords, metatags, triggers,
                    hashtags, or any web link that doesn't resolve to
                    https://fly-inn.com
                  </li>
                  <li>
                    Changing, modifying or altering any part of our Trademarks
                    or branding
                  </li>
                  <li>Using our Trademarks as part of a larger mark</li>
                  <li>Using our Trademarks in plural or possessive forms</li>
                  <li>Using variations or translations of our Trademarks</li>
                  <li>Using old versions of our Trademarks</li>
                  <li>
                    Using "FlyInn" or "Fly-Inn" in lieu of generic terms like
                    "vacation rental"
                  </li>
                  <li>
                    Using our Trademarks in a way that suggests partnership or
                    endorsement without authorization
                  </li>
                  <li>
                    Using our Trademarks in false or misleading advertising
                  </li>
                  <li>
                    Using our Trademarks to defame or disparage FlyInn or our
                    Community
                  </li>
                  <li>
                    Displaying our Trademarks more prominently than your own
                  </li>
                  <li>Using our Trademarks more frequently than necessary</li>
                  <li>Displaying our Trademarks in violation of any law</li>
                  <li>Copying or appropriating our trade dress</li>
                </ol>
              </div>
            </section>

            {/* Permission Section */}
            <section className="mb-10">
              <div className="bg-amber-50 border-l-4 border-amber-400 p-6 rounded-r-lg">
                <h3 className="text-lg font-semibold text-gray-900 mb-3">
                  Request Permission
                </h3>
                <p className="text-gray-700 text-base">
                  If you would like permission to use our Trademarks, please
                  email us at{" "}
                  <a
                    href="mailto:legal@fly-inn.com"
                    className="text-[#AF2322] hover:text-[#8B1B1B] underline font-medium"
                  >
                    legal@fly-inn.com
                  </a>
                  . With the exceptions outlined below, you may only use our
                  Trademarks with our express written consent.
                </p>
              </div>
            </section>

            {/* What is allowed Section */}
            <section className="mb-10">
              <div className="bg-green-50 border border-green-200 rounded-lg p-6">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  What IS Allowed:
                </h2>
                <ol className="list-decimal ml-6 space-y-3 text-gray-700 text-base">
                  <li>
                    Using our name correctly: FlyInn, Fly-Inn, and FlyInn, LLC
                    are all appropriate
                  </li>
                  <li>
                    Using our Trademarks only as adjectives modifying a generic
                    name or noun
                  </li>
                  <li>
                    Using our name to describe your relationship with FlyInn
                    (e.g., "FlyInn Host")
                  </li>
                  <li>
                    Using our name to talk about products or services offered on
                    the Platform (e.g., "FlyInn Listing," "FlyInn Squawks")
                  </li>
                  <li>
                    Using the most current versions of our Trademarks to
                    hyperlink to https://fly-inn.com
                  </li>
                  <li>
                    Using and displaying our attribution statement: "FlyInn,
                    LLC's [Mark] and the [Logo name or description] are
                    trademarks and/or service marks of FlyInn, LLC."
                  </li>
                </ol>
              </div>
            </section>

            {/* User Information Note */}
            <section className="mb-10">
              <div className="bg-gray-50 rounded-lg p-4">
                <p className="text-gray-600 text-sm italic">
                  For users that register on our website, we also store the
                  personal information they provide in their user profile. All
                  users can see, edit, or delete their personal information at
                  any time (except they cannot change their username). Website
                  administrators can also see and edit that information.
                </p>
              </div>
            </section>

            {/* Community Section */}
            <section className="mb-10">
              <div className="bg-blue-50 border-l-4 border-blue-400 p-6 rounded-r-lg">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  COMMUNITY
                </h2>
                <p className="text-gray-700 text-base">
                  Maintaining our Trademark's value and goodwill benefits our
                  whole Community. Please support your Community by emailing us
                  at{" "}
                  <a
                    href="mailto:legal@fly-inn.com"
                    className="text-[#AF2322] hover:text-[#8B1B1B] underline font-medium"
                  >
                    legal@fly-inn.com
                  </a>{" "}
                  if you notice any violation of the guidelines set forth in
                  this Trademark Policy.
                </p>
              </div>
            </section>
          </div>
        </div>

        {/* Related Policies */}
        <div className="mt-8 bg-white rounded-lg shadow-sm p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">
            Related Policies
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Link
              href="/public/content-copyright-policy"
              className="text-[#AF2322] hover:text-[#8B1B1B] underline text-base"
            >
              Content and Copyright Policy →
            </Link>
            <Link
              href="/public/terms-of-service"
              className="text-[#AF2322] hover:text-[#8B1B1B] underline text-base"
            >
              Terms of Service →
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
